import 'dart:convert';
import 'dart:io';
import 'dart:ui';

import 'package:androidx_graphics_shapes/material_shapes.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:libmonet/shapes/material_expressive_shape.dart';

import 'optical_center.dart';
import 'safe_interior.dart';

void main() {
  test('precompute endpoint-safe Material shape interiors', () {
    final options = jsonDecode(
      Platform.environment['MONET_SAFE_AREAS_OPTIONS'] ??
          (throw StateError(
            'Run dart tool/precompute_safe_areas.dart instead',
          )),
    ) as Map<String, dynamic>;
    final ratios = (options['ratios'] as List).cast<num>();
    final clearance = (options['clearance'] as num).toDouble();
    final tolerance = (options['tolerance'] as num).toDouble();
    final entries = <Map<String, Object?>>[];
    for (final shape in MaterialExpressiveShape.values) {
      final path = shape.polygon.toPath();
      final outline = SafeInteriorOutline(shape.polygon.cubics);
      final optical = findOpticalCenter(
        cubics: shape.polygon.cubics,
        path: path,
        areaCentroid: outline.areaCentroid,
      );
      final preferredCenter = optical.center;
      entries.add({
        'shape': shape.name,
        'preferredCenter': [preferredCenter.dx, preferredCenter.dy],
        'centerMethod': optical.method.name,
        'reflectionAxisCount': optical.axisCount,
        'areaCentroid': [outline.areaCentroid.dx, outline.areaCentroid.dy],
        'convexHullCentroid': [
          optical.hullCentroid.dx,
          optical.hullCentroid.dy,
        ],
        'rectangles': [
          for (final ratio in ratios)
            (() {
              final Rect? rect;
              try {
                rect = outline.findAtCenter(
                  aspectRatio: ratio.toDouble(),
                  center: preferredCenter,
                  clearance: clearance,
                  tolerance: tolerance,
                );
              } on StateError catch (error) {
                throw StateError(
                  '${shape.name} ratio=$ratio: ${error.message}',
                );
              }
              return {
                'aspectRatio': ratio,
                'rect': rect == null
                    ? null
                    : [rect.left, rect.top, rect.right, rect.bottom],
              };
            })(),
        ],
      });
    }
    final output = File(options['output'] as String);
    output.parent.createSync(recursive: true);
    output.writeAsStringSync(
      '${const JsonEncoder.withIndent('  ').convert({
        'schemaVersion': 5,
        'generator': 'tool/precompute_safe_areas.dart',
        'source': 'androidx_graphics_shapes MaterialShapes via MaterialExpressiveShape',
        'coordinates': 'Original package unit coordinates; no bounds renormalization',
        'objective': 'Largest rectangle at the generated optical center for each aspect ratio',
        'centerPolicy': 'Reflection axes: their intersection when multiple, maximum outline clearance when one, convex-hull centroid when none',
        'rectFormat': ['left', 'top', 'right', 'bottom'],
        'clearance': clearance,
        'tolerance': tolerance,
        'numericGuard': SafeInteriorOutline.numericGuard,
        'method': 'Generated optical center plus fixed-center bisection; recursive cubic control bounds depth 24; inconclusive rejected',
        'scope': 'Static endpoints only; no intermediate morph containment required',
        'shapes': entries,
      })}\n',
    );
    final dartOutput = options['dartOutput'] as String?;
    if (dartOutput != null) {
      final buffer = StringBuffer(
        '// Generated by tool/precompute_safe_areas.dart; do not edit.\n'
        '// Static endpoint interiors, clearance $clearance source units, '
        'fixed-center tolerance $tolerance.\n'
        "import 'dart:ui';\n"
        "import '../material_expressive_shape.dart';\n\n"
        'const materialShapeAreaCentroidData = '
        '<MaterialExpressiveShape, Offset>{\n',
      );
      for (final shape in entries) {
        final centroid = shape['areaCentroid']! as List<double>;
        buffer.writeln(
          '  MaterialExpressiveShape.${shape['shape']}: '
          'Offset(${centroid.join(', ')}),',
        );
      }
      buffer.writeln('};\n');
      buffer.writeln(
        'const materialShapePreferredCenterData = '
        '<MaterialExpressiveShape, Offset>{',
      );
      for (final shape in entries) {
        final center = shape['preferredCenter']! as List<double>;
        buffer.writeln(
          '  MaterialExpressiveShape.${shape['shape']}: '
          'Offset(${center.join(', ')}),',
        );
      }
      buffer.writeln('};\n');
      buffer.writeln(
        'const materialShapeSafeAreaData = '
        '<MaterialExpressiveShape, List<Rect>>{',
      );
      for (final shape in entries) {
        buffer.writeln('  MaterialExpressiveShape.${shape['shape']}: [');
        for (final entry in shape['rectangles']! as List) {
          final rect = entry['rect'] as List<double>?;
          if (rect != null) {
            buffer.writeln('    Rect.fromLTRB(${rect.join(', ')}),');
          }
        }
        buffer.writeln('  ],');
      }
      buffer.writeln('};');
      final dartFile = File(dartOutput);
      dartFile.parent.createSync(recursive: true);
      dartFile.writeAsStringSync(buffer.toString());
    }
    // ignore: avoid_print
    print(
      'Wrote ${entries.length} shapes × ${ratios.length} ratios to ${output.path}',
    );
  });
}
