import 'dart:convert';
import 'dart:io';

import 'package:androidx_graphics_shapes/material_shapes.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:libmonet/shapes/material_expressive_shape.dart';

import 'safe_interior.dart';

void main() {
  test('precompute endpoint-safe Material shape interiors', () {
    final options = jsonDecode(
      Platform.environment['MONET_SAFE_AREAS_OPTIONS'] ??
          (throw StateError(
            'Run dart tool/precompute_safe_areas.dart instead',
          )),
    ) as Map<String, dynamic>;
    final ratios = (options['ratios'] as List).cast<num>();
    final clearance = (options['clearance'] as num).toDouble();
    final entries = <Map<String, Object?>>[];
    for (final shape in MaterialExpressiveShape.values) {
      final outline = SafeInteriorOutline(shape.polygon.cubics);
      final center = shape.polygon.toPath().getBounds().center;
      entries.add({
        'shape': shape.name,
        'anchor': [center.dx, center.dy],
        'rectangles': [
          for (final ratio in ratios)
            (() {
              final rect = outline.find(
                aspectRatio: ratio.toDouble(),
                clearance: clearance,
                center: center,
              );
              return {
                'aspectRatio': ratio,
                'rect': rect == null
                    ? null
                    : [rect.left, rect.top, rect.right, rect.bottom],
              };
            })(),
        ],
      });
    }
    final output = File(options['output'] as String);
    output.parent.createSync(recursive: true);
    output.writeAsStringSync(
      '${const JsonEncoder.withIndent('  ').convert({
        'schemaVersion': 2,
        'generator': 'tool/precompute_safe_areas.dart',
        'source': 'androidx_graphics_shapes MaterialShapes via MaterialExpressiveShape',
        'coordinates': 'Original package unit coordinates; no bounds renormalization',
        'anchor': 'Per-shape path bounds center (see shapes[].anchor)',
        'rectFormat': ['left', 'top', 'right', 'bottom'],
        'clearance': clearance,
        'numericGuard': SafeInteriorOutline.numericGuard,
        'method': 'Recursive cubic control bounds, depth 24; inconclusive rejected',
        'scope': 'Static endpoints only; no intermediate morph containment required',
        'shapes': entries,
      })}\n',
    );
    final dartOutput = options['dartOutput'] as String?;
    if (dartOutput != null) {
      final buffer = StringBuffer(
        '// Generated by tool/precompute_safe_areas.dart; do not edit.\n'
        '// Static endpoint interiors, clearance $clearance source units.\n'
        "import 'dart:ui';\n"
        "import '../material_expressive_shape.dart';\n\n"
        'const materialShapeSafeAreaData = <MaterialExpressiveShape, List<Rect>>{\n',
      );
      for (final shape in entries) {
        buffer.writeln('  MaterialExpressiveShape.${shape['shape']}: [');
        for (final entry in shape['rectangles']! as List) {
          final rect = entry['rect'] as List<double>?;
          if (rect != null) {
            buffer.writeln('    Rect.fromLTRB(${rect.join(', ')}),');
          }
        }
        buffer.writeln('  ],');
      }
      buffer.writeln('};');
      final dartFile = File(dartOutput);
      dartFile.parent.createSync(recursive: true);
      dartFile.writeAsStringSync(buffer.toString());
    }
    // ignore: avoid_print
    print(
      'Wrote ${entries.length} shapes × ${ratios.length} ratios to ${output.path}',
    );
  });
}
