// Modified and maintained by open-source contributors, on behalf of libmonet.
//
// Original notice:
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is automatically generated. Do not modify it.

import 'dart:ui' show Color;

import 'package:libmonet/argb_srgb_xyz_lab.dart';

String hexFromColor(Color color, {bool leadingHashSign = true}) {
  return hexFromArgb(color.argb, leadingHashSign: leadingHashSign);
}

/// Converts an ARGB integer to a 6-character RGB hex string.
///
/// **Note:** The alpha channel is discarded. This function always returns
/// a 6-character hex code (e.g., `#FF5733`), which is the standard format
/// for CSS colors and does not support transparency. If you need to preserve
/// alpha, use an 8-character ARGB hex format instead.
///
/// Returns a hex string with or without a leading `#` based on [leadingHashSign].
String hexFromArgb(int argb, {bool leadingHashSign = true}) {
  final red = redFromArgb(argb);
  final green = greenFromArgb(argb);
  final blue = blueFromArgb(argb);
  return '${leadingHashSign ? '#' : ''}'
      '${red.toRadixString(16).padLeft(2, '0').toUpperCase()}'
      '${green.toRadixString(16).padLeft(2, '0').toUpperCase()}'
      '${blue.toRadixString(16).padLeft(2, '0').toUpperCase()}';
}

int? argbFromHex(String hex) {
  hex = hex.replaceAll('#', '');
  if (hex.length == 6) {
    hex = 'FF$hex'; // add alpha if it's missing
  }
  return int.tryParse(hex, radix: 16);
}

Color? colorFromHex(String hex) {
  final argb = argbFromHex(hex);
  if (argb == null) {
    return null;
  }
  return Color(argb);
}

extension HexOnColor on Color {
  String get hex => hexFromArgb(argb);
}

extension Argb on Color {
  // The `value` property is deprecated, but it is equivalent to `toARGB32()`.
  int get argb => toARGB32();
}
