// Modified and maintained by open-source contributors, on behalf of libmonet.
//
// Original notice:
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is automatically generated. Do not modify it.

import 'dart:ui' show Color;

import 'package:libmonet/argb_srgb_xyz_lab.dart';

String hexFromColor(Color color, {bool leadingHashSign = true}) {
  return hexFromArgb(color.value, leadingHashSign: leadingHashSign);
}

String hexFromArgb(int argb, {bool leadingHashSign = true}) {
  final red = redFromArgb(argb);
  final green = greenFromArgb(argb);
  final blue = blueFromArgb(argb);
  return '${leadingHashSign ? '#' : ''}'
      '${red.toRadixString(16).padLeft(2, '0').toUpperCase()}'
      '${green.toRadixString(16).padLeft(2, '0').toUpperCase()}'
      '${blue.toRadixString(16).padLeft(2, '0').toUpperCase()}';
}

int? argbFromHex(String hex) {
  return int.tryParse(hex.replaceAll('#', ''), radix: 16);
}
