// Refresh and verify the Google Fonts catalog and offline raster metrics.
// dart tool/generate_fonts.dart --write [--refresh-metadata] [--package-config=...]
// dart tool/generate_fonts.dart --check [--package-config=...]
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const metadataUrl = 'https://fonts.google.com/metadata/fonts';
const pillowVersion = '12.1.1';

class FontVariant {
  const FontVariant(this.weight, this.italic, this.hash, this.length);
  final int weight;
  final bool italic;
  final String hash;
  final int length;
  String get pickerName => '$weight${italic ? 'i' : ''}';
}

class FontSource {
  const FontSource(this.directory, this.version, this.hash, this.families);
  final Directory directory;
  final String version;
  final String hash;
  final Map<String, List<FontVariant>> families;
}

Map<String, List<FontVariant>> parseLiteDescriptors(String source) {
  final families = RegExp(
    r"^    '([^']+)': \{",
    multiLine: true,
  ).allMatches(source).toList();
  final variants = RegExp(
    r"GoogleFontsVariant\(\s*fontWeight: FontWeight\.w(\d+),\s*"
    r"fontStyle: FontStyle\.(normal|italic),\s*\): (?:const )?"
    r"GoogleFontsFile\(\s*'([0-9a-f]{64})',\s*(\d+),",
  );
  final result = <String, List<FontVariant>>{};
  for (var i = 0; i < families.length; i++) {
    final family = families[i].group(1)!;
    final block = source.substring(
      families[i].end,
      i + 1 == families.length ? source.length : families[i + 1].start,
    );
    final entries = variants
        .allMatches(block)
        .map(
          (match) => FontVariant(
            int.parse(match.group(1)!),
            match.group(2) == 'italic',
            match.group(3)!,
            int.parse(match.group(4)!),
          ),
        )
        .toList();
    if (entries.isEmpty ||
        entries.length !=
            RegExp(r'GoogleFontsVariant\(').allMatches(block).length ||
        result.containsKey(family) ||
        entries.map((entry) => entry.pickerName).toSet().length !=
            entries.length) {
      throw FormatException(
        'Missing, duplicate, or malformed variants: $family',
      );
    }
    result[family] = entries;
  }
  if (result.isEmpty) throw const FormatException('No Lite descriptors found');
  return result;
}

FontSource readFontSource(File packageConfig) {
  final config = jsonDecode(packageConfig.readAsStringSync()) as Map;
  final entry = (config['packages'] as List).cast<Map>().singleWhere(
    (entry) => entry['name'] == 'google_fonts',
  );
  final directory = Directory.fromUri(
    packageConfig.absolute.uri.resolve(entry['rootUri'] as String),
  );
  final pubspec = File('${directory.path}/pubspec.yaml').readAsStringSync();
  final version = RegExp(
    r'^version: (\S+)',
    multiLine: true,
  ).firstMatch(pubspec)!.group(1)!;
  final source = File('${directory.path}/lib/src/google_fonts_lite.dart')
      .readAsStringSync();
  return FontSource(
    directory,
    version,
    sha256.convert(utf8.encode(source)).toString(),
    parseLiteDescriptors(source),
  );
}

String dartString(String value) =>
    "'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'";

String generateCatalog(FontSource source, Map<String, dynamic> metadata) {
  const categories = [
    'serif',
    'sans-serif',
    'display',
    'handwriting',
    'monospace',
  ];
  final languages = <String>{'all'};
  final families = source.families.keys.toList()..sort();
  for (final family in families) {
    final details = metadata[family] as Map?;
    if (details == null ||
        !categories.contains(details['category']) ||
        details['subsets'] is! List) {
      throw FormatException(
        'Missing or invalid metadata: $family. Use --refresh-metadata.',
      );
    }
    languages.addAll((details['subsets'] as List).cast<String>());
  }
  final sortedLanguages = languages.toList()..sort();
  final out = StringBuffer('''// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/generate_fonts.dart.
// Source package: google_fonts-${source.version}.
// Source descriptor SHA-256: ${source.hash}.
// Metadata source: $metadataUrl.

''');
  void list(String name, Iterable<String> values) {
    out.writeln('const $name = <String>[');
    for (final value in values) {
      out.writeln('  ${dartString(value)},');
    }
    out.writeln('];\n');
  }

  list('googleFontCategories', categories);
  list('googleFontLanguages', sortedLanguages);
  list('googleFontsList', families);
  out.writeln('const googleFontsDetails = <String, Map<String, String>>{');
  for (final family in families) {
    final details = metadata[family] as Map;
    final variants = source.families[family]!.toList()
      ..sort((a, b) {
        final weight = a.weight.compareTo(b.weight);
        return weight != 0
            ? weight
            : (a.italic ? 1 : 0).compareTo(b.italic ? 1 : 0);
      });
    final subsets = (details['subsets'] as List).cast<String>().join(',');
    out.writeln('  ${dartString(family)}: {');
    out.writeln(
      "    'category': ${dartString(details['category'] as String)},",
    );
    out.writeln(
      "    'variants': ${dartString(variants.map((v) => v.pickerName).join(','))},",
    );
    out.writeln("    'subsets': ${dartString(subsets)},");
    out.writeln('  },');
  }
  out.writeln('};');
  return out.toString();
}

Future<Map<String, dynamic>> fetchMetadata(FontSource source) async {
  final client = HttpClient()..connectionTimeout = const Duration(seconds: 60);
  try {
    final request = await client.getUrl(Uri.parse(metadataUrl));
    final response = await request.close();
    if (response.statusCode != 200) {
      throw HttpException('Metadata HTTP ${response.statusCode}');
    }
    final text = await utf8.decodeStream(response);
    final body = jsonDecode(text.substring(text.indexOf('{'))) as Map;
    final all = <String, Map>{
      for (final item in (body['familyMetadataList'] as List).cast<Map>())
        item['family'] as String: item,
    };
    const categories = {
      'Serif': 'serif',
      'Sans Serif': 'sans-serif',
      'Display': 'display',
      'Handwriting': 'handwriting',
      'Monospace': 'monospace',
    };
    final result = <String, dynamic>{};
    final families = source.families.keys.toList()..sort();
    for (final family in families) {
      final item = all[family];
      if (item == null || !categories.containsKey(item['category'])) {
        throw FormatException('No Google Fonts metadata for $family');
      }
      result[family] = {
        'category': categories[item['category']],
        'subsets':
            (item['subsets'] as List)
                .cast<String>()
                .where((s) => s != 'menu')
                .toList()
              ..sort(),
      };
    }
    return result;
  } finally {
    client.close(force: true);
  }
}

Future<void> run(
  String executable,
  List<String> arguments, {
  String? workingDirectory,
}) async {
  final process = await Process.start(
    executable,
    arguments,
    workingDirectory: workingDirectory,
  );
  await Future.wait([
    stdout.addStream(process.stdout),
    stderr.addStream(process.stderr),
  ]);
  final code = await process.exitCode;
  if (code != 0) {
    throw ProcessException(executable, arguments, 'Exited with $code', code);
  }
}

Future<String> rasterPython(Directory root) async {
  final environment = Directory(
    '${root.path}/.dart_tool/font_generation/python',
  );
  final executable = Platform.isWindows
      ? '${environment.path}/Scripts/python.exe'
      : '${environment.path}/bin/python';
  if (!File(executable).existsSync()) {
    await run(Platform.isWindows ? 'python' : 'python3', [
      '-m',
      'venv',
      environment.path,
    ]);
  }
  final probe = await Process.run(executable, [
    '-c',
    'import PIL; print(PIL.__version__)',
  ]);
  if (probe.exitCode != 0 || probe.stdout.toString().trim() != pillowVersion) {
    await run(executable, ['-m', 'pip', 'install', 'Pillow==$pillowVersion']);
  }
  return executable;
}

String fingerprint(File file) =>
    sha256.convert(file.readAsBytesSync()).toString();
String normalize(String value) =>
    value.replaceAll(RegExp('[^A-Za-z0-9]'), '').toLowerCase();

Future<void> main(List<String> args) async {
  if (args.length == 1 && args.single == '--help') {
    stdout.writeln(
      'dart tool/generate_fonts.dart --write [--refresh-metadata] [--package-config=PATH]\n'
      'dart tool/generate_fonts.dart --check [--package-config=PATH]',
    );
    return;
  }
  final mode = args
      .where((arg) => ['--write', '--check'].contains(arg))
      .toList();
  if (mode.length != 1 ||
      args.any(
        (arg) =>
            !['--write', '--check', '--refresh-metadata'].contains(arg) &&
            !arg.startsWith('--package-config='),
      )) {
    throw ArgumentError(
      'Use --write [--refresh-metadata] or --check [--package-config=PATH]',
    );
  }
  final refresh = args.contains('--refresh-metadata');
  if (mode.single == '--check' && refresh) {
    throw ArgumentError('--check does not use the network');
  }
  final root = Directory.fromUri(Platform.script.resolve('../'));
  final configArgs = args
      .where((arg) => arg.startsWith('--package-config='))
      .toList();
  if (configArgs.length > 1) throw ArgumentError('Specify one package config');
  final config = File(
    configArgs.isEmpty
        ? '${root.path}/.dart_tool/package_config.json'
        : configArgs.single.substring('--package-config='.length),
  );
  final source = readFontSource(config);
  final metadataFile = File(
    '${root.path}/tool/data/google_fonts_metadata.json',
  );
  final metadata = refresh
      ? await fetchMetadata(source)
      : jsonDecode(metadataFile.readAsStringSync()) as Map<String, dynamic>;
  final catalogText = generateCatalog(source, metadata);
  final catalog = File('${root.path}/lib/fonts/google_fonts_catalog.g.dart');
  final metrics = File('${root.path}/lib/fonts/font_height_equalizer.g.dart');
  final manifest = File('${root.path}/tool/data/google_fonts_generation.json');
  final generator = File(
    '${root.path}/lib/fonts/generate_font_height_equalizer.py',
  );
  if (mode.single == '--check') {
    final provenance = jsonDecode(manifest.readAsStringSync()) as Map;
    if (catalog.readAsStringSync() != catalogText ||
        provenance['version'] != source.version ||
        provenance['descriptors'] != source.hash ||
        provenance['metadata'] != fingerprint(metadataFile) ||
        provenance['metrics'] != fingerprint(metrics) ||
        provenance['rasterizer'] != fingerprint(generator) ||
        provenance['pillow'] != pillowVersion) {
      throw StateError(
        'Font data is stale. Run tool/generate_fonts.dart --write --refresh-metadata with the same package config.',
      );
    }
    stdout.writeln(
      'Verified ${source.families.length} families from google_fonts ${source.version} (offline).',
    );
    return;
  }
  final staging = await Directory('${root.path}/.dart_tool/font_generation')
      .create(recursive: true);
  final stagedMetrics = File('${staging.path}/font_height_equalizer.g.dart');
  final python = await rasterPython(root);
  await run(python, [
    generator.path,
    '--package-dir',
    source.directory.path,
    '--output',
    stagedMetrics.path,
    '--cache-dir',
    '${staging.path}/ttf',
  ], workingDirectory: root.path);
  // The established Pillow rasterizer keeps the perceptual metric unchanged.
  // The public workflow, package resolution, metadata, and freshness gate are Dart.
  await run(Platform.resolvedExecutable, ['format', stagedMetrics.path]);
  final metricText = stagedMetrics.readAsStringSync();
  if (!metricText.contains(
    '// Source package: google_fonts-${source.version}.',
  )) {
    throw StateError('Rasterizer used a different Google Fonts package');
  }
  final metricKeys = RegExp(
    r"^  '([^']+)':",
    multiLine: true,
  ).allMatches(metricText).map((m) => m.group(1)!).toSet();
  final exclusions =
      source.families.keys
          .where((family) => !metricKeys.contains(normalize(family)))
          .toList()
        ..sort();
  metadataFile.parent.createSync(recursive: true);
  metadataFile.writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(metadata)}\n',
  );
  catalog.writeAsStringSync(catalogText);
  metrics.writeAsStringSync(metricText);
  final provenance = {
    'version': source.version,
    'descriptors': source.hash,
    'metadata': fingerprint(metadataFile),
    'metrics': fingerprint(metrics),
    'rasterizer': fingerprint(generator),
    'pillow': pillowVersion,
    'metricExclusions': exclusions,
  };
  manifest.writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(provenance)}\n',
  );
  stdout.writeln(
    'Generated ${source.families.length} picker families. Metrics unavailable for: ${exclusions.join(', ')}',
  );
}
