import 'package:androidx_graphics_shapes/material_shapes.dart';

/// Names for the fork’s Material catalog; no geometry is duplicated here.
enum MaterialExpressiveShape {
  circle('Circle'),
  square('Square'),
  slanted('Slanted'),
  arch('Arch'),
  semiCircle('SemiCircle'),
  oval('Oval'),
  pill('Pill'),
  triangle('Triangle'),
  arrow('Arrow'),
  fan('Fan'),
  diamond('Diamond'),
  clamShell('ClamShell'),
  pentagon('Pentagon'),
  gem('Gem'),
  verySunny('VerySunny'),
  sunny('Sunny'),
  cookie4Sided('Cookie4Sided'),
  cookie6Sided('Cookie6Sided'),
  cookie7Sided('Cookie7Sided'),
  cookie9Sided('Cookie9Sided'),
  cookie12Sided('Cookie12Sided'),
  clover4Leaf('Clover4Leaf'),
  clover8Leaf('Clover8Leaf'),
  burst('Burst'),
  softBurst('SoftBurst'),
  boom('Boom'),
  softBoom('SoftBoom'),
  flower('Flower'),
  puffy('Puffy'),
  puffyDiamond('PuffyDiamond'),
  ghostish('Ghostish'),
  pixelCircle('PixelCircle'),
  pixelTriangle('PixelTriangle'),
  bun('Bun'),
  heart('Heart');

  const MaterialExpressiveShape(this.label);

  final String label;

  /// The package’s normalized polygon, including features needed for morphing.
  RoundedPolygon get polygon => switch (this) {
    circle => MaterialShapes.circle,
    square => MaterialShapes.square,
    slanted => MaterialShapes.slanted,
    arch => MaterialShapes.arch,
    semiCircle => MaterialShapes.semiCircle,
    oval => MaterialShapes.oval,
    pill => MaterialShapes.pill,
    triangle => MaterialShapes.triangle,
    arrow => MaterialShapes.arrow,
    fan => MaterialShapes.fan,
    diamond => MaterialShapes.diamond,
    clamShell => MaterialShapes.clamShell,
    pentagon => MaterialShapes.pentagon,
    gem => MaterialShapes.gem,
    verySunny => MaterialShapes.verySunny,
    sunny => MaterialShapes.sunny,
    cookie4Sided => MaterialShapes.cookie4Sided,
    cookie6Sided => MaterialShapes.cookie6Sided,
    cookie7Sided => MaterialShapes.cookie7Sided,
    cookie9Sided => MaterialShapes.cookie9Sided,
    cookie12Sided => MaterialShapes.cookie12Sided,
    clover4Leaf => MaterialShapes.clover4Leaf,
    clover8Leaf => MaterialShapes.clover8Leaf,
    burst => MaterialShapes.burst,
    softBurst => MaterialShapes.softBurst,
    boom => MaterialShapes.boom,
    softBoom => MaterialShapes.softBoom,
    flower => MaterialShapes.flower,
    puffy => MaterialShapes.puffy,
    puffyDiamond => MaterialShapes.puffyDiamond,
    ghostish => MaterialShapes.ghostish,
    pixelCircle => MaterialShapes.pixelCircle,
    pixelTriangle => MaterialShapes.pixelTriangle,
    bun => MaterialShapes.bun,
    heart => MaterialShapes.heart,
  };
}
