#!/usr/bin/env python3
"""Generate Google Fonts catalog data used by font pickers.

The family list is taken from the locked `google_fonts` package so runtime
selection matches the app dependency. Category/subset/variant metadata is taken
from the public Google Fonts metadata endpoint and intersected with that package
family list.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.request import urlopen

sys.path.insert(0, str(Path(__file__).parent))
import generate_font_height_equalizer as font_table

_METADATA_URL = "https://fonts.google.com/metadata/fonts"
_CATEGORY_MAP = {
    "Serif": "serif",
    "Sans Serif": "sans-serif",
    "Display": "display",
    "Handwriting": "handwriting",
    "Monospace": "monospace",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default="lib/fonts/google_fonts_catalog.g.dart",
        help="Dart file to write.",
    )
    parser.add_argument(
        "--metadata-json",
        help="Optional cached fonts.google.com metadata JSON file.",
    )
    return parser.parse_args()


def load_metadata(path: str | None) -> dict:
    if path is not None:
        raw = Path(path).read_text()
    else:
        with urlopen(_METADATA_URL, timeout=60) as response:
            raw = response.read().decode("utf-8")
    return json.loads(raw[raw.find("{") :])


def dart_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def fallback_variants(family: str, index: tuple[dict[str, str], dict[str, str], dict[str, str]]) -> list[str]:
    values = []
    for variant in sorted(font_table.variants_for_family(family, index), key=lambda item: item.weight):
        values.append(str(variant.weight))
    return list(dict.fromkeys(values)) or ["400"]


def main() -> None:
    args = parse_args()
    package_dir = font_table.find_google_fonts_package()
    index = font_table.google_fonts_index(package_dir)
    package_families = sorted(index[0])

    metadata = load_metadata(args.metadata_json)
    metadata_by_family = {
        item["family"]: item for item in metadata.get("familyMetadataList", [])
    }
    missing_metadata = [
        family for family in package_families if family not in metadata_by_family
    ]
    catalog_families = [
        family for family in package_families if family in metadata_by_family
    ]

    details: dict[str, dict[str, str]] = {}
    subsets = {"all"}
    categories = ["serif", "sans-serif", "display", "handwriting", "monospace"]
    for family in catalog_families:
        item = metadata_by_family[family]
        category = _CATEGORY_MAP.get(item.get("category", ""), "serif")
        family_subsets = [subset for subset in item.get("subsets", []) if subset != "menu"]
        subsets.update(family_subsets)
        variants = sorted(item.get("fonts", {}).keys(), key=lambda value: (int(re.sub(r"\D", "", value) or "400"), "i" in value))
        details[family] = {
            "category": category,
            "variants": ",".join(variants or fallback_variants(family, index)),
            "subsets": ",".join(family_subsets),
        }

    lines = [
        "// GENERATED CODE - DO NOT MODIFY BY HAND.",
        "// Generated by lib/fonts/generate_google_fonts_catalog.py.",
        f"// Source package: {package_dir.name}.",
        f"// Metadata source: {_METADATA_URL}.",
        "",
        "const googleFontCategories = <String>[",
    ]
    lines.extend(f"  {dart_string(category)}," for category in categories)
    lines.extend(['];', '', 'const googleFontLanguages = <String>['])
    lines.extend(f"  {dart_string(subset)}," for subset in sorted(subsets))
    lines.extend(['];', '', 'const googleFontsList = <String>['])
    lines.extend(f"  {dart_string(family)}," for family in catalog_families)
    lines.extend(['];', '', 'const googleFontsDetails = <String, Map<String, String>>{'])
    for family in catalog_families:
        detail = details[family]
        lines.append(
            f"  {dart_string(family)}: "
            f"{{'category': {dart_string(detail['category'])}, "
            f"'variants': {dart_string(detail['variants'])}, "
            f"'subsets': {dart_string(detail['subsets'])}}},"
        )
    lines.extend(['};', ''])

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    print(
        f"wrote {output} with {len(catalog_families)} families; "
        f"excluded {len(missing_metadata)} package families missing metadata: "
        f"{', '.join(missing_metadata) if missing_metadata else 'none'}"
    )


if __name__ == "__main__":
    main()
